### ISSUE TITLE
Nincs CI

### ISSUE THREAD

**Issue by DemeterNorbert** [BME-MIT-IET/iet-hf2021-dr-jupekzo#2]
A projektben rengetek teszt található de nincs CI beüzemelve. Nem lehet tudni ezért, hogy ha fel is pusholjuk a munkákat, akkor az a teszteken átmegy-e és ezáltal nem okoz nem kívánt működést.

**Comment by Henya14** [comment]
Meg lett csinálva a #3 PR-ban
