### ISSUE TITLE
Seq: super hivás hiánya a konstruktorban.

### ISSUE THREAD

**Issue by Csabi1998** [BME-MIT-IET/iet-hf2021-dr-jupekzo#29]
![image](https://user-images.githubusercontent.com/61312438/117328995-7bc78c00-ae94-11eb-89e8-a910e0da3779.png)
Három konstruktorban is hiányzik a super hívás ami miatt a this hibát dob.

**Comment by Henya14** [comment]
A superek meghívása elkerülhtetlen végtelen ciklust alakít ki, sajnos 😓
