### ISSUE TITLE
CodeCoverage mérése

### ISSUE THREAD

**Issue by DemeterNorbert** [BME-MIT-IET/iet-hf2021-dr-jupekzo#48]
Jelenleg nem mérjük a codecoverage-ot és megszeretnénk nézni, hogy mennyi. Ezekután majd tudjuk bővíteni ha kell.

**Comment by Henya14** [comment]
Egyszer kiküldte az üzenetet, de utána már nem küldte többet. Hiába töltök fel neki bármilyen reportot hibát dob és semmilyen segítséget nem ad, hogy mi romlott el, szóval elvileg minden fel van konfigurálva csak a codecov nem kooperál 😅
![image](https://user-images.githubusercontent.com/61234783/118361151-4dc80300-b58a-11eb-973f-2c8385286d38.png)

**Comment by Henya14** [comment]
Annyit sikerült még hozzáadni a build folyamathoz, hogy minden alakalommal feltölti a coverage reportot codecov-ra. De valamiért nem akarja megjeleníteni az eredményeket. Nem értem miért mivel a tutoriált lelkiismeretesen végigkövettem. 😟
