### ISSUE TITLE
Statikus analízis Sonar Clouddal 1

### ISSUE THREAD

**Issue by DemeterNorbert** [BME-MIT-IET/iet-hf2021-dr-jupekzo#7]
Rengeteg kritikus & major hibát jelzett ki a sonar Cloud, azokat át kell nézni és kijavítani, amit ki lehet.

**Comment by Henya14** [comment]
#5  #6

**Comment by Henya14** [comment]
#9

**Comment by DemeterNorbert** [comment]
Lett #31 folytatásképpen, mert sok volt már benne.
